crates = use_extension("@rules_rust//crate_universe:extensions.bzl", "crate")

crates.spec(
    package = "mimalloc",
    version = "0.1.52",
    features = ["override"],
)

crates.spec(
    package = "hecs",
    version = "0.11.1",
    default_features = False,
    features = ["std"],
)

crates.spec(
    package = "glam",
    version = "0.33.2",
    default_features = False,
    features = ["std", "all-types"]
)

crates.from_specs()
use_repo(crates, "crates")
