load("@rules_rust//rust:defs.bzl", "rust_binary")

rust_binary(
    name = "ink",
    srcs = [
        "src/ink.rs",
        "src/editor.rs",
        "src/handles.rs",
    ],
    deps = [
        "@ink//crates/glfw-sys:glfw_sys",
        "@crates//:mimalloc",
        "@crates//:hecs",
        "@crates//:glam",
    ],
    edition = "2024",
    visibility = ["@ink//:__pkg__"]
)
