load("@rules_rust//rust:defs.bzl", "rust_library")
load("@rules_rust_bindgen//:defs.bzl", "rust_bindgen")
load("//tools:out_dir.bzl", "rust_out_dir")

rust_bindgen(
    name = "bindings",
    bindgen_flags = [
        "--allowlist-function=glfw.*",
        "--allowlist-type=GLFW.*",
        "--allowlist-var=GLFW.*",
        "--rust-edition=2018",
    ],
    cc_lib = "@glfw//:glfw_header",
    header = "@glfw//:glfw_header_file",
    merge_cc_lib_objects_into_rlib = False,
)

rust_out_dir(
    name = "bindings_out_dir",
    srcs = [":bindings"],
)

rust_library(
    name = "glfw_sys",
    srcs = ["src/lib.rs"],
    deps = [":bindings_out_dir"],
    link_deps = ["@glfw//:glfw"],
    edition = "2018",
    visibility = ["@ink//crates:__subpackages__"]
)
