load("@rules_rust_bindgen//:defs.bzl", "rust_bindgen_toolchain")
load("@rules_cc//cc:defs.bzl", "cc_library")
load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "out_dir_builder",
    srcs = ["out_dir_builder.py"],
)

# Define CcInfo which rust_bindgen_toolchain needs and wouldn't exist else.
cc_library(
    name = "libclang",
    srcs = ["@llvm_toolchain_llvm//:libclang"],
)

rust_bindgen_toolchain(
    name = "bindgen_toolchain_impl",
    bindgen = "@rules_rust_bindgen//3rdparty:bindgen",
    clang = "@llvm_toolchain_llvm//:bin/clang",
    libclang = ":libclang",
)

toolchain(
    name = "bindgen_toolchain",
    toolchain = ":bindgen_toolchain_impl",
    toolchain_type = "@rules_rust_bindgen//:toolchain_type",
)
